"""epic_13_add_books_and_update_chat_session

Revision ID: b6063ba30336
Revises: c2d4e6f8a9b0
Create Date: 2026-03-24 10:59:10.891795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# 导入自定义类型，用于 UTCDateTime 列
from app.db.types import UTCDateTime


# revision identifiers, used by Alembic.
revision: str = 'b6063ba30336'
down_revision: Union[str, Sequence[str], None] = 'c2d4e6f8a9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('cover_url', sa.String(length=1024), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.Column('ai_friend_id', sa.Integer(), nullable=True),
    sa.Column('reading_location', sa.String(length=255), nullable=True),
    sa.Column('create_time', UTCDateTime(), nullable=False),
    sa.Column('update_time', UTCDateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ai_friend_id'], ['friends.id'], name=op.f('fk_books_ai_friend_id_friends')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books'))
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_books_id'), ['id'], unique=False)

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_type', sa.String(length=32), nullable=False, server_default='normal'))
        batch_op.add_column(sa.Column('knowledge_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_column('knowledge_id')
        batch_op.drop_column('session_type')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_id'))

    op.drop_table('books')
    # ### end Alembic commands ###
